insert into author (age, name, genre) values (72, 'Spense', 'drama');
insert into author (age, name, genre) values (54, 'Emery', 'comedy');
insert into author (age, name, genre) values (74, 'Sammy', 'drama');
insert into author (age, name, genre) values (95, 'Chen', 'comedy');
insert into author (age, name, genre) values (47, 'Mikey', 'thriller');
insert into author (age, name, genre) values (94, 'Liz', 'action');
insert into author (age, name, genre) values (51, 'Elfrieda', 'drama');
insert into author (age, name, genre) values (27, 'Beulah', 'drama');
insert into author (age, name, genre) values (47, 'Melba', 'action');
insert into author (age, name, genre) values (70, 'Sherry', 'action');

insert into book (isbn, title, genre) values ('383283212-2', 'Marriage Material', 'drama');
insert into book (isbn, title, genre) values ('543356985-3', 'Day of the Falcon', 'thriller');
insert into book (isbn, title, genre) values ('153628099-2', 'Standing Up', 'romance');
insert into book (isbn, title, genre) values ('096362542-X', 'Rolling Thunder', 'comedy');
insert into book (isbn, title, genre) values ('978076212-4', 'American Pie Presents Beta House (American Pie 6: Beta House)', 'thriller');
insert into book (isbn, title, genre) values ('146211436-9', 'Craigslist Killer, The ', 'romance');
insert into book (isbn, title, genre) values ('594304753-0', '20 Feet from Stardom (Twenty Feet from Stardom)', 'action');
insert into book (isbn, title, genre) values ('165102692-0', 'Bhaag Milka Bhaag', 'action');
insert into book (isbn, title, genre) values ('201580343-2', 'Nick Fury: Agent of S.H.I.E.L.D.', 'comedy');
insert into book (isbn, title, genre) values ('553453783-3', 'Lies and Illusions', 'action');
insert into book (isbn, title, genre) values ('762498252-8', 'Divo, Il', 'drama');
insert into book (isbn, title, genre) values ('722105698-6', 'Cross: The Arthur Blessitt Story, The', 'romance');
insert into book (isbn, title, genre) values ('960728929-3', 'Hand, The (Ruka)', 'action');
insert into book (isbn, title, genre) values ('268362030-6', 'Caught Inside', 'romance');
insert into book (isbn, title, genre) values ('471524151-X', 'The Hungover Games', 'drama');
insert into book (isbn, title, genre) values ('043517467-3', 'Who Killed Nancy?', 'comedy');
insert into book (isbn, title, genre) values ('544653546-4', 'La guerre des tuques', 'action');
insert into book (isbn, title, genre) values ('517884211-1', 'Lisbela e o Prisioneiro (Lisbela and the Prisoner)', 'romance');
insert into book (isbn, title, genre) values ('570923120-7', 'Wankers, The (Les branleuses)', 'action');
insert into book (isbn, title, genre) values ('184858305-2', 'Criminals', 'romance');
insert into book (isbn, title, genre) values ('105376200-3', 'Goodbye Again', 'comedy');
insert into book (isbn, title, genre) values ('999562729-9', 'Lifeboat', 'action');
insert into book (isbn, title, genre) values ('515277985-4', 'Jerry Maguire', 'romance');
insert into book (isbn, title, genre) values ('890574418-4', 'Turn of Faith', 'action');
insert into book (isbn, title, genre) values ('574807674-8', 'Children of the Corn: Revelation', 'thriller');
insert into book (isbn, title, genre) values ('429683794-X', 'Seinto Seiya: Legend of Sanctuary (Seinto Seiya: Legend of Sanctuary)', 'action');
insert into book (isbn, title, genre) values ('015658573-1', 'Attack Force', 'drama');
insert into book (isbn, title, genre) values ('689511633-8', 'Lightspeed', 'thriller');
insert into book (isbn, title, genre) values ('356228464-0', 'Grease 2', 'thriller');
insert into book (isbn, title, genre) values ('236209631-9', 'Outlaw Blues', 'romance');
insert into book (isbn, title, genre) values ('479894821-7', 'Attack of the 5 Ft. 2 Women (National Lampoon''s Attack of the 5 Ft 2 Woman)', 'comedy');
insert into book (isbn, title, genre) values ('468350594-0', 'Fireman, The', 'action');
insert into book (isbn, title, genre) values ('628220493-3', 'Greedy', 'action');
insert into book (isbn, title, genre) values ('238847212-1', 'Hi Tessa (Czesc Tereska)', 'romance');
insert into book (isbn, title, genre) values ('401993022-8', 'Behold a Pale Horse', 'comedy');
insert into book (isbn, title, genre) values ('518847172-8', 'Stage Struck', 'romance');
insert into book (isbn, title, genre) values ('157702040-5', 'Stage Door', 'romance');
insert into book (isbn, title, genre) values ('822478096-1', 'Charley Varrick', 'thriller');
insert into book (isbn, title, genre) values ('796371591-3', 'Rabbit à la Berlin (Królik po berlinsku)', 'drama');
insert into book (isbn, title, genre) values ('311364211-6', 'Ordinary People', 'romance');
insert into book (isbn, title, genre) values ('171097733-7', 'All the Brothers Were Valiant', 'comedy');
insert into book (isbn, title, genre) values ('876329773-6', 'On the Road to Emmaus (Emmauksen tiellä)', 'romance');
insert into book (isbn, title, genre) values ('850437921-3', 'Everybody''s Got Somebody... Not Me', 'action');
insert into book (isbn, title, genre) values ('172672756-4', 'Muppet Movie, The', 'action');
insert into book (isbn, title, genre) values ('168001252-5', 'Harmontown', 'comedy');
insert into book (isbn, title, genre) values ('148057679-4', 'Mushrooming (Seenelkäik)', 'thriller');
insert into book (isbn, title, genre) values ('732072410-3', 'Insider, The', 'action');
insert into book (isbn, title, genre) values ('825721780-8', 'Superstar: The Karen Carpenter Story', 'romance');
insert into book (isbn, title, genre) values ('502555919-7', 'Varsity Blues', 'action');
insert into book (isbn, title, genre) values ('574807187-8', 'Washington Heights', 'action');
insert into book (isbn, title, genre) values ('011278903-X', 'Beyond the Lights', 'comedy');
insert into book (isbn, title, genre) values ('446233412-4', 'Good Wife, The', 'action');
insert into book (isbn, title, genre) values ('404897901-9', 'House, The (A Casa)', 'romance');
insert into book (isbn, title, genre) values ('158124121-6', 'Shallow Hal', 'comedy');
insert into book (isbn, title, genre) values ('640647188-1', 'Take, The', 'drama');
insert into book (isbn, title, genre) values ('378334171-X', 'Buy the Ticket, Take the Ride: Hunter S. Thompson on Film', 'drama');
insert into book (isbn, title, genre) values ('870000185-6', 'Lower City (Cidade Baixa)', 'thriller');
insert into book (isbn, title, genre) values ('691232823-7', 'Madeleine', 'action');
insert into book (isbn, title, genre) values ('038642748-8', 'Chinese Roulette (Chinesisches Roulette)', 'comedy');
insert into book (isbn, title, genre) values ('980474609-3', 'Mambo Italiano', 'romance');
insert into book (isbn, title, genre) values ('154558291-2', 'Blinkity Blank', 'thriller');
insert into book (isbn, title, genre) values ('641633673-1', 'Thousand Clouds of Peace, A (Mil nubes de paz cercan el cielo, amor, jamás acabarás de ser amor)', 'drama');
insert into book (isbn, title, genre) values ('506099588-7', 'My Flesh and Blood', 'action');
insert into book (isbn, title, genre) values ('258935336-7', 'Girls! Girls! Girls!', 'action');
insert into book (isbn, title, genre) values ('556548526-6', 'Pillow Book, The', 'action');
insert into book (isbn, title, genre) values ('161972170-8', 'Dead Husbands', 'drama');
insert into book (isbn, title, genre) values ('942834832-5', 'Item, The', 'romance');
insert into book (isbn, title, genre) values ('748330807-9', 'Little Ashes', 'action');
insert into book (isbn, title, genre) values ('501815033-5', 'Rio Sex Comedy', 'romance');
insert into book (isbn, title, genre) values ('618852735-X', 'Steam of Life (Miesten vuoro)', 'romance');
insert into book (isbn, title, genre) values ('949012493-1', 'Blindness', 'drama');
insert into book (isbn, title, genre) values ('000598114-X', 'Rally ''Round the Flag, Boys!', 'drama');
insert into book (isbn, title, genre) values ('001819924-0', 'Bend of the River', 'comedy');
insert into book (isbn, title, genre) values ('580967328-7', 'Red Lights', 'comedy');
insert into book (isbn, title, genre) values ('901621872-6', 'Jakob the Liar', 'romance');
insert into book (isbn, title, genre) values ('801105673-5', 'Road to Singapore', 'drama');
insert into book (isbn, title, genre) values ('664390532-X', 'Spoilers, The', 'drama');
insert into book (isbn, title, genre) values ('324478209-4', 'Don''t Look in the Basement!', 'comedy');
insert into book (isbn, title, genre) values ('854513061-9', 'Can''t Buy Me Love', 'thriller');
insert into book (isbn, title, genre) values ('374030199-6', 'The 11 Commandments', 'romance');
insert into book (isbn, title, genre) values ('161755304-2', 'Undertow', 'action');
insert into book (isbn, title, genre) values ('389270369-8', '8th Wonderland', 'drama');
insert into book (isbn, title, genre) values ('296986890-3', 'Premium Rush', 'action');
insert into book (isbn, title, genre) values ('063625519-0', 'Shadows (Senki)', 'thriller');
insert into book (isbn, title, genre) values ('846601610-4', 'Doctor, The', 'thriller');
insert into book (isbn, title, genre) values ('724157978-X', 'Reincarnation', 'comedy');
insert into book (isbn, title, genre) values ('080150444-9', 'Isle, The (Seom)', 'thriller');
insert into book (isbn, title, genre) values ('546153696-4', 'Ossos', 'drama');
insert into book (isbn, title, genre) values ('128290327-6', 'Scandal (Shubun)', 'drama');
insert into book (isbn, title, genre) values ('470913731-5', 'Freeze Me', 'thriller');
insert into book (isbn, title, genre) values ('479642535-7', 'Female Perversions', 'action');
insert into book (isbn, title, genre) values ('501130723-9', 'Secret, A (Un secret)', 'action');
insert into book (isbn, title, genre) values ('703612512-8', 'Dead Pool, The', 'romance');
insert into book (isbn, title, genre) values ('229431859-5', 'Hostel: Part III ', 'drama');
insert into book (isbn, title, genre) values ('714026692-1', 'Ninja: Shadow of a Tear', 'comedy');
insert into book (isbn, title, genre) values ('876131382-3', 'Adrift (À Deriva)', 'romance');
insert into book (isbn, title, genre) values ('179381159-8', 'Blink', 'drama');
insert into book (isbn, title, genre) values ('536356401-7', 'Caught Up', 'drama');
insert into book (isbn, title, genre) values ('093666043-0', 'Swarm, The', 'romance');
insert into book (isbn, title, genre) values ('715325823-X', 'Mutiny on the Bounty', 'drama');