insert into author (age, name, genre, id) values (23, "Mark Janel", "Anthology", 1);
insert into author (age, name, genre, id) values (43, "Olivia Goy", "Horror", 2);
insert into author (age, name, genre, id) values (51, "Quartis Young", "Anthology", 3);
insert into author (age, name, genre, id) values (34, "Joana Nimar", "History", 4);
insert into author (age, name, genre, id) values (38, "Alicia Tom", "Anthology", 5);
insert into author (age, name, genre, id) values (56, "Katy Loin", "Anthology", 6);

insert into bestseller (title, ranking, author_id) values ('Escape from Suburbia: Beyond the American Dream', 59, 2);
insert into bestseller (title, ranking, author_id) values ('Earth vs. the Spider', 30, 2);
insert into bestseller (title, ranking, author_id) values ('Stick', 85, 1);
insert into bestseller (title, ranking, author_id) values ('112 Weddings', 89, 3);
insert into bestseller (title, ranking, author_id) values ('The Girl from the Marsh Croft', 98, 5);
insert into bestseller (title, ranking, author_id) values ('Kissed by Winter (Vinterkyss)', 88, 1);
insert into bestseller (title, ranking, author_id) values ('Tai Chi Hero', 39, 3);
insert into bestseller (title, ranking, author_id) values ('Terror on a Train (Time Bomb)', 1, 5);
insert into bestseller (title, ranking, author_id) values ('Magic Gloves, The (Los guantes mágicos)', 47, 5);
insert into bestseller (title, ranking, author_id) values ('Everything or Nothing: The Untold Story of 007', 79, 2);
insert into bestseller (title, ranking, author_id) values ('Drive, He Said', 79, 4);
insert into bestseller (title, ranking, author_id) values ('Extraordinary Adventures of Adèle Blanc-Sec, The', 50, 5);
insert into bestseller (title, ranking, author_id) values ('Home Page', 97, 5);
insert into bestseller (title, ranking, author_id) values ('Two Bits', 92, 5);
insert into bestseller (title, ranking, author_id) values ('How Bruce Lee Changed the World', 1, 1);
insert into bestseller (title, ranking, author_id) values ('Weekend', 58, 3);
insert into bestseller (title, ranking, author_id) values ('Devil and Daniel Webster, The (All That Money Can Buy)', 50, 2);
insert into bestseller (title, ranking, author_id) values ('Cranford', 68, 3);
insert into bestseller (title, ranking, author_id) values ('Religulous', 3, 5);
insert into bestseller (title, ranking, author_id) values ('The Dust Bowl', 85, 4);
insert into bestseller (title, ranking, author_id) values ('Sink the Bismark!', 59, 4);
insert into bestseller (title, ranking, author_id) values ('American Ninja 3: Blood Hunt', 69, 3);
insert into bestseller (title, ranking, author_id) values ('Dr. Gillespie''s New Assistant', 5, 1);
insert into bestseller (title, ranking, author_id) values ('Gestapo''s Last Orgy, The (L''ultima orgia del III Reich)', 45, 2);
insert into bestseller (title, ranking, author_id) values ('Glass House, The', 1, 3);
insert into bestseller (title, ranking, author_id) values ('Dawn Patrol, The (Flight Commander)', 99, 5);
insert into bestseller (title, ranking, author_id) values ('Iris', 64, 3);
insert into bestseller (title, ranking, author_id) values ('Calling Bulldog Drummond', 48, 4);
insert into bestseller (title, ranking, author_id) values ('Lake House, The', 9, 4);
insert into bestseller (title, ranking, author_id) values ('Terry Pratchett: Choosing to Die', 31, 4);
insert into bestseller (title, ranking, author_id) values ('All This, and Heaven Too', 89, 3);
insert into bestseller (title, ranking, author_id) values ('Fate of a Man (Sudba cheloveka)', 40, 2);
insert into bestseller (title, ranking, author_id) values ('Arthur 2: On the Rocks', 27, 4);
insert into bestseller (title, ranking, author_id) values ('Great Waltz, The', 57, 3);
insert into bestseller (title, ranking, author_id) values ('Cop', 50, 2);
insert into bestseller (title, ranking, author_id) values ('Hole, The', 56, 3);
insert into bestseller (title, ranking, author_id) values ('Series 7: The Contenders', 84, 1);
insert into bestseller (title, ranking, author_id) values ('Song of Sparrows, The (Avaze gonjeshk-ha)', 53, 1);
insert into bestseller (title, ranking, author_id) values ('Stories We Tell', 66, 1);
insert into bestseller (title, ranking, author_id) values ('That''s Black Entertainment', 13, 5);
insert into bestseller (title, ranking, author_id) values ('Tin Star, The', 58, 2);
insert into bestseller (title, ranking, author_id) values ('Clash by Night', 72, 1);
insert into bestseller (title, ranking, author_id) values ('Where''s Poppa?', 20, 5);
insert into bestseller (title, ranking, author_id) values ('Pola X', 38, 3);
insert into bestseller (title, ranking, author_id) values ('100 Bloody Acres', 26, 1);
insert into bestseller (title, ranking, author_id) values ('Detroit Rock City', 90, 2);
insert into bestseller (title, ranking, author_id) values ('Starlift', 86, 3);
insert into bestseller (title, ranking, author_id) values ('Beau Brummel', 99, 1);
insert into bestseller (title, ranking, author_id) values ('American Hardcore', 37, 5);
insert into bestseller (title, ranking, author_id) values ('Chances Are', 13, 2);
insert into bestseller (title, ranking, author_id) values ('Underneath', 48, 4);
insert into bestseller (title, ranking, author_id) values ('Boy Interrupted', 15, 1);
insert into bestseller (title, ranking, author_id) values ('Epic Movie', 46, 1);
insert into bestseller (title, ranking, author_id) values ('Bugsy Malone', 22, 1);
insert into bestseller (title, ranking, author_id) values ('Something from Nothing: The Art of Rap', 34, 2);
insert into bestseller (title, ranking, author_id) values ('Flipper', 30, 3);
insert into bestseller (title, ranking, author_id) values ('Invisible Ray, The', 74, 1);
insert into bestseller (title, ranking, author_id) values ('Mississippi Grind', 5, 5);
insert into bestseller (title, ranking, author_id) values ('Kill Switch', 34, 2);
insert into bestseller (title, ranking, author_id) values ('Phantom Lover, The (Ye ban ge sheng)', 3, 5);
insert into bestseller (title, ranking, author_id) values ('There Be Dragons', 70, 5);
insert into bestseller (title, ranking, author_id) values ('You Killed Me First', 4, 4);
insert into bestseller (title, ranking, author_id) values ('I Am Bruce Lee', 63, 2);
insert into bestseller (title, ranking, author_id) values ('The Green', 24, 4);
insert into bestseller (title, ranking, author_id) values ('Played', 64, 3);
insert into bestseller (title, ranking, author_id) values ('New in Town', 60, 1);
insert into bestseller (title, ranking, author_id) values ('Faces of Death 2', 87, 5);
insert into bestseller (title, ranking, author_id) values ('The Deep Six', 58, 3);
insert into bestseller (title, ranking, author_id) values ('Beowulf & Grendel', 38, 4);
insert into bestseller (title, ranking, author_id) values ('Past Midnight', 39, 3);
insert into bestseller (title, ranking, author_id) values ('Mall', 17, 4);
insert into bestseller (title, ranking, author_id) values ('Secret Ballot (Raye makhfi)', 74, 5);
insert into bestseller (title, ranking, author_id) values ('Sherman''s March', 54, 3);
insert into bestseller (title, ranking, author_id) values ('Happy End', 41, 5);
insert into bestseller (title, ranking, author_id) values ('Submarine X-1', 73, 1);
insert into bestseller (title, ranking, author_id) values ('Cowboys, The', 36, 3);
insert into bestseller (title, ranking, author_id) values ('Série noire', 95, 5);
insert into bestseller (title, ranking, author_id) values ('Faces', 68, 1);
insert into bestseller (title, ranking, author_id) values ('Aberdeen', 59, 4);
insert into bestseller (title, ranking, author_id) values ('Thérèse: The Story of Saint Thérèse of Lisieux', 46, 5);
insert into bestseller (title, ranking, author_id) values ('Together (Tillsammans)', 59, 1);
insert into bestseller (title, ranking, author_id) values ('About Last Night', 94, 4);
insert into bestseller (title, ranking, author_id) values ('Missing Star, The (La stella che non c''è)', 29, 1);
insert into bestseller (title, ranking, author_id) values ('Miami Vice', 63, 4);
insert into bestseller (title, ranking, author_id) values ('Shake Hands with the Devil', 42, 5);
insert into bestseller (title, ranking, author_id) values ('Zandalee', 42, 1);
insert into bestseller (title, ranking, author_id) values ('Castaway', 18, 1);
insert into bestseller (title, ranking, author_id) values ('You Ain''t Seen Nothin'' Yet (Vous n''avez encore rien vu)', 83, 5);
insert into bestseller (title, ranking, author_id) values ('Ice Age 4: Continental Drift', 5, 4);
insert into bestseller (title, ranking, author_id) values ('Barretts of Wimpole Street, The (a.k.a. Forbidden Alliance)', 65, 4);
insert into bestseller (title, ranking, author_id) values ('Rovaniemen markkinoilla', 22, 3);
insert into bestseller (title, ranking, author_id) values ('Gingerbread Man, The', 21, 5);
insert into bestseller (title, ranking, author_id) values ('Love Punch, The', 3, 3);
insert into bestseller (title, ranking, author_id) values ('Souls for Sale', 51, 4);
insert into bestseller (title, ranking, author_id) values ('Crusades, The', 81, 5);
insert into bestseller (title, ranking, author_id) values ('Public Speaking', 20, 5);
insert into bestseller (title, ranking, author_id) values ('Prophecy 3: The Ascent, The', 39, 3);
insert into bestseller (title, ranking, author_id) values ('Bloodsport', 55, 3);
insert into bestseller (title, ranking, author_id) values ('Fearless Hyena II (Long teng hu yue)', 60, 1);
insert into bestseller (title, ranking, author_id) values ('Comme un chef', 46, 3);