insert into author (name, age, genre) values ('Martino', 44, 'romance');
insert into author (name, age, genre) values ('Mab', 31, 'mystery');
insert into author (name, age, genre) values ('Merrily', 37, 'horror');
insert into author (name, age, genre) values ('Hayes', 59, 'sci-fi');
insert into author (name, age, genre) values ('Cathe', 58, 'drama');
insert into author (name, age, genre) values ('Pia', 33, 'sci-fi');
insert into author (name, age, genre) values ('Constantine', 51, 'fantasy');
insert into author (name, age, genre) values ('Dorthy', 62, 'adventure');
insert into author (name, age, genre) values ('Juli', 65, 'comedy');
insert into author (name, age, genre) values ('Cordie', 46, 'mystery');
insert into author (name, age, genre) values ('Paxton', 67, 'fantasy');
insert into author (name, age, genre) values ('Jean', 50, 'fantasy');
insert into author (name, age, genre) values ('Xenia', 62, 'comedy');
insert into author (name, age, genre) values ('Waly', 57, 'fantasy');
insert into author (name, age, genre) values ('Judi', 68, 'sci-fi');
insert into author (name, age, genre) values ('Kasey', 50, 'sci-fi');
insert into author (name, age, genre) values ('Tallie', 33, 'sci-fi');
insert into author (name, age, genre) values ('Jamesy', 47, 'romance');
insert into author (name, age, genre) values ('Ritchie', 66, 'comedy');
insert into author (name, age, genre) values ('Allistir', 41, 'romance');
insert into author (name, age, genre) values ('Prisca', 64, 'romance');
insert into author (name, age, genre) values ('Regina', 65, 'action');
insert into author (name, age, genre) values ('Gloria', 67, 'mystery');
insert into author (name, age, genre) values ('Maribel', 42, 'fantasy');
insert into author (name, age, genre) values ('Valeda', 70, 'mystery');
insert into author (name, age, genre) values ('Thorsten', 50, 'action');
insert into author (name, age, genre) values ('Byron', 59, 'sci-fi');
insert into author (name, age, genre) values ('Denver', 60, 'fantasy');
insert into author (name, age, genre) values ('Abagail', 56, 'drama');
insert into author (name, age, genre) values ('Christan', 69, 'romance');
insert into author (name, age, genre) values ('Jehanna', 31, 'horror');
insert into author (name, age, genre) values ('Vincents', 32, 'fantasy');
insert into author (name, age, genre) values ('Eolande', 36, 'romance');
insert into author (name, age, genre) values ('Tressa', 60, 'mystery');
insert into author (name, age, genre) values ('Elisabet', 53, 'sci-fi');
insert into author (name, age, genre) values ('Winonah', 40, 'mystery');
insert into author (name, age, genre) values ('Kearney', 64, 'comedy');
insert into author (name, age, genre) values ('Myriam', 54, 'drama');
insert into author (name, age, genre) values ('De witt', 48, 'fantasy');
insert into author (name, age, genre) values ('Amelie', 39, 'drama');
insert into author (name, age, genre) values ('Klaus', 47, 'thriller');
insert into author (name, age, genre) values ('Damaris', 55, 'action');
insert into author (name, age, genre) values ('Rowland', 68, 'comedy');
insert into author (name, age, genre) values ('Nicki', 58, 'sci-fi');
insert into author (name, age, genre) values ('Cayla', 33, 'comedy');
insert into author (name, age, genre) values ('Ethe', 30, 'comedy');
insert into author (name, age, genre) values ('Timotheus', 66, 'comedy');
insert into author (name, age, genre) values ('Shell', 45, 'horror');
insert into author (name, age, genre) values ('Loni', 62, 'sci-fi');
insert into author (name, age, genre) values ('Marcello', 33, 'drama');
insert into author (name, age, genre) values ('Katinka', 47, 'fantasy');
insert into author (name, age, genre) values ('Kessia', 36, 'fantasy');
insert into author (name, age, genre) values ('Carolin', 59, 'action');
insert into author (name, age, genre) values ('Pietra', 46, 'action');
insert into author (name, age, genre) values ('Diannne', 41, 'sci-fi');
insert into author (name, age, genre) values ('Traci', 57, 'mystery');
insert into author (name, age, genre) values ('Reinhard', 48, 'adventure');
insert into author (name, age, genre) values ('Freddy', 56, 'fantasy');
insert into author (name, age, genre) values ('Olympe', 69, 'adventure');
insert into author (name, age, genre) values ('Hillier', 44, 'horror');
insert into author (name, age, genre) values ('Donnie', 59, 'romance');
insert into author (name, age, genre) values ('Eada', 46, 'adventure');
insert into author (name, age, genre) values ('Joey', 43, 'action');
insert into author (name, age, genre) values ('Loren', 50, 'adventure');
insert into author (name, age, genre) values ('Kakalina', 60, 'adventure');
insert into author (name, age, genre) values ('Brenda', 58, 'action');
insert into author (name, age, genre) values ('Lucretia', 46, 'sci-fi');
insert into author (name, age, genre) values ('Red', 36, 'drama');
insert into author (name, age, genre) values ('Casper', 40, 'drama');
insert into author (name, age, genre) values ('Gaven', 35, 'sci-fi');
insert into author (name, age, genre) values ('Duke', 37, 'fantasy');
insert into author (name, age, genre) values ('Chilton', 30, 'horror');
insert into author (name, age, genre) values ('Hansiain', 58, 'romance');
insert into author (name, age, genre) values ('Malvina', 37, 'action');
insert into author (name, age, genre) values ('Rosina', 65, 'drama');
insert into author (name, age, genre) values ('Ailyn', 38, 'sci-fi');
insert into author (name, age, genre) values ('Franky', 47, 'thriller');
insert into author (name, age, genre) values ('Bess', 60, 'action');
insert into author (name, age, genre) values ('Sela', 38, 'sci-fi');
insert into author (name, age, genre) values ('Korney', 34, 'adventure');
insert into author (name, age, genre) values ('Trevar', 51, 'fantasy');
insert into author (name, age, genre) values ('Smith', 48, 'thriller');
insert into author (name, age, genre) values ('Aylmer', 43, 'thriller');
insert into author (name, age, genre) values ('Ebony', 68, 'thriller');
insert into author (name, age, genre) values ('Casey', 60, 'sci-fi');
insert into author (name, age, genre) values ('Athena', 34, 'thriller');
insert into author (name, age, genre) values ('Dre', 32, 'mystery');
insert into author (name, age, genre) values ('Abbye', 41, 'mystery');
insert into author (name, age, genre) values ('Melisse', 49, 'mystery');
insert into author (name, age, genre) values ('Aurie', 64, 'action');
insert into author (name, age, genre) values ('Rebecca', 51, 'sci-fi');
insert into author (name, age, genre) values ('Jessa', 65, 'thriller');
insert into author (name, age, genre) values ('Pat', 53, 'mystery');
insert into author (name, age, genre) values ('Pen', 35, 'action');
insert into author (name, age, genre) values ('Hortensia', 43, 'drama');
insert into author (name, age, genre) values ('Elsa', 37, 'drama');
insert into author (name, age, genre) values ('Lazarus', 33, 'adventure');
insert into author (name, age, genre) values ('Rebekkah', 46, 'mystery');
insert into author (name, age, genre) values ('Analise', 37, 'horror');
insert into author (name, age, genre) values ('Selie', 36, 'adventure');

insert into book (isbn, title) values ('749193014-X', 'Stepford Wives, The');
insert into book (isbn, title) values ('554470165-2', 'Men Cry Bullets');
insert into book (isbn, title) values ('456784105-0', 'Sleeping Beauty, The (La belle endormie)');
insert into book (isbn, title) values ('291774167-8', 'Pierrot le fou');
insert into book (isbn, title) values ('999943054-6', 'Play Girl');
insert into book (isbn, title) values ('009708522-7', 'Bloodline');
insert into book (isbn, title) values ('944166313-1', 'My Left Eye Sees Ghosts (Ngo joh aan gin diy gwai)');
insert into book (isbn, title) values ('644447053-6', 'Headquarters (Päämaja) ');
insert into book (isbn, title) values ('248610968-4', 'Tell Me and I Will Forget');
insert into book (isbn, title) values ('060238420-6', 'Mission to Mir');
insert into book (isbn, title) values ('589982444-1', 'Harem');
insert into book (isbn, title) values ('277771980-2', 'Beneath Hill 60');
insert into book (isbn, title) values ('353329412-9', 'Julie');
insert into book (isbn, title) values ('847257044-4', 'Escape from L.A.');
insert into book (isbn, title) values ('277264731-5', 'Notorious Bettie Page, The');
insert into book (isbn, title) values ('215928499-8', 'In Old Arizona');
insert into book (isbn, title) values ('343847799-8', 'Passion of Darkly Noon, The');
insert into book (isbn, title) values ('665620951-3', 'Long Way Down, A');
insert into book (isbn, title) values ('072304138-5', 'Countdown');
insert into book (isbn, title) values ('793987273-7', 'Parallel Sons');
insert into book (isbn, title) values ('158057148-4', 'Shadowzone');
insert into book (isbn, title) values ('769808873-1', 'It Should Happen to You');
insert into book (isbn, title) values ('398723217-X', 'He Said, She Said');
insert into book (isbn, title) values ('525190205-0', 'Just a Little Harmless Sex');
insert into book (isbn, title) values ('440314315-6', 'Battlestar Galactica');
insert into book (isbn, title) values ('131489129-4', 'Meatballs');
insert into book (isbn, title) values ('233352442-1', 'Goat, The');
insert into book (isbn, title) values ('953247173-1', 'Alive and Ticking (Ein Tick anders)');
insert into book (isbn, title) values ('113860884-X', 'Berlin Calling');
insert into book (isbn, title) values ('158534077-4', 'Esa ja Vesa - auringonlaskun ratsastajat');
insert into book (isbn, title) values ('960471163-6', 'Child, The');
insert into book (isbn, title) values ('686137159-9', 'Three-Step Dance');
insert into book (isbn, title) values ('345432004-6', 'Vision Quest');
insert into book (isbn, title) values ('330746342-X', 'Trek Nation');
insert into book (isbn, title) values ('207721930-0', 'Play Motel');
insert into book (isbn, title) values ('709005422-5', 'Great Yokai War, The (Yôkai daisensô)');
insert into book (isbn, title) values ('150978398-9', 'Carol Channing: Larger Than Life');
insert into book (isbn, title) values ('339134749-X', 'Fate Is the Hunter');
insert into book (isbn, title) values ('335670038-3', 'Waist Deep');
insert into book (isbn, title) values ('558655649-9', 'Snow White and the Seven Dwarfs');
insert into book (isbn, title) values ('395461862-1', 'Inn in Tokyo, An (Tôkyô no yado)');
insert into book (isbn, title) values ('110948098-9', 'Mad Ron''s Prevues from Hell');
insert into book (isbn, title) values ('927800048-5', 'Zatoichi Meets Yojimbo (Zatôichi to Yôjinbô) (Zatôichi 20)');
insert into book (isbn, title) values ('472071075-1', 'America, America');
insert into book (isbn, title) values ('722337962-6', 'Knight and Day');
insert into book (isbn, title) values ('912290283-X', '1-900');
insert into book (isbn, title) values ('729798609-7', 'Keeper, The');
insert into book (isbn, title) values ('075565017-4', 'Suicide Shop, The (Le magasin des suicides) ');
insert into book (isbn, title) values ('690691571-1', 'Embodiment of Evil (Encarnação do Demônio)');
insert into book (isbn, title) values ('365736845-0', 'English Vinglish');
insert into book (isbn, title) values ('084766103-2', 'Clockwise');
insert into book (isbn, title) values ('473510066-0', 'Fire Down Below');
insert into book (isbn, title) values ('448756916-8', 'Voyage of the Damned');
insert into book (isbn, title) values ('236046911-8', 'All the Young Men');
insert into book (isbn, title) values ('177648161-5', 'My Brilliant Career');
insert into book (isbn, title) values ('602580207-6', 'Terror Train');
insert into book (isbn, title) values ('344051467-6', 'Ghost Ship, The');
insert into book (isbn, title) values ('296580960-0', 'Beauty Day');
insert into book (isbn, title) values ('647496506-1', 'Citizen Cohn');
insert into book (isbn, title) values ('168987445-7', 'Passionada');
insert into book (isbn, title) values ('207182815-1', 'Dirty Harry');
insert into book (isbn, title) values ('317815866-9', '3 Blind Mice');
insert into book (isbn, title) values ('497380646-3', 'Immortals');
insert into book (isbn, title) values ('685164954-3', 'Guy Thing, A');
insert into book (isbn, title) values ('885991271-7', 'Phenix City Story, The');
insert into book (isbn, title) values ('172731437-9', 'People vs. Larry Flynt, The');
insert into book (isbn, title) values ('144886317-1', 'Kansas Raiders');
insert into book (isbn, title) values ('973487077-7', 'Last Life in the Universe (Ruang rak noi nid mahasan)');
insert into book (isbn, title) values ('484452602-2', 'Rain Man');
insert into book (isbn, title) values ('303232143-3', 'Raw Deal');
insert into book (isbn, title) values ('467360000-2', 'Free Soul, A');
insert into book (isbn, title) values ('639707545-1', 'Naughty Girl');
insert into book (isbn, title) values ('929154338-1', 'Exodus');
insert into book (isbn, title) values ('264128173-2', 'Summer of ''62 (Cartouches gauloises)');
insert into book (isbn, title) values ('990195422-3', '49th Parallel');
insert into book (isbn, title) values ('627099569-8', 'Gen-Y Cops (Te jing xin ren lei 2) (Gen-X Cops 2: Metal Mayhem) (Metal Mayhem)');
insert into book (isbn, title) values ('176101755-1', 'Firepower');
insert into book (isbn, title) values ('760256900-8', 'Decline of Western Civilization Part II: The Metal Years, The');
insert into book (isbn, title) values ('215711390-8', 'Ciao, Professore! (Io speriamo che me la cavo)');
insert into book (isbn, title) values ('300330537-9', 'Still of the Night');
insert into book (isbn, title) values ('499230608-X', 'Sasha (Sascha)');
insert into book (isbn, title) values ('653889553-0', 'White Irish Drinkers');
insert into book (isbn, title) values ('895098708-2', 'Harold and Maude');
insert into book (isbn, title) values ('119217138-1', 'Echelon Conspiracy');
insert into book (isbn, title) values ('170748014-1', 'Lake House, The');
insert into book (isbn, title) values ('991245022-1', 'Altman');
insert into book (isbn, title) values ('545973861-X', 'Dead Men Don''t Wear Plaid');
insert into book (isbn, title) values ('295929051-8', 'Fast Five (Fast and the Furious 5, The)');
insert into book (isbn, title) values ('553754393-1', 'Corpo Celeste');
insert into book (isbn, title) values ('714916398-X', 'Ghost in the Machine (a.k.a. Deadly Terror)');
insert into book (isbn, title) values ('869988054-5', 'Blot, The');
insert into book (isbn, title) values ('357739987-2', 'Twilight of the Ice Nymphs');
insert into book (isbn, title) values ('988351903-6', 'This Ain''t California');
insert into book (isbn, title) values ('593844971-5', 'They Live by Night');
insert into book (isbn, title) values ('668262535-9', 'Halloweentown II: Kalabar''s Revenge');
insert into book (isbn, title) values ('070596740-9', 'Losin'' It');
insert into book (isbn, title) values ('419951122-9', 'Madeline');
insert into book (isbn, title) values ('241241427-0', 'Picture Bride (Bijo photo)');
insert into book (isbn, title) values ('280087358-2', 'Dracula''s Daughter');
insert into book (isbn, title) values ('969053675-3', 'Criminal Law');


insert into author_book (author_id, book_id) values (100, 40);
insert into author_book (author_id, book_id) values (38, 11);
insert into author_book (author_id, book_id) values (53, 64);
insert into author_book (author_id, book_id) values (21, 38);
insert into author_book (author_id, book_id) values (35, 38);
insert into author_book (author_id, book_id) values (18, 74);
insert into author_book (author_id, book_id) values (89, 37);
insert into author_book (author_id, book_id) values (7, 5);
insert into author_book (author_id, book_id) values (75, 12);
insert into author_book (author_id, book_id) values (92, 16);
insert into author_book (author_id, book_id) values (40, 67);
insert into author_book (author_id, book_id) values (45, 27);
insert into author_book (author_id, book_id) values (96, 28);
insert into author_book (author_id, book_id) values (51, 21);
insert into author_book (author_id, book_id) values (62, 6);
insert into author_book (author_id, book_id) values (80, 54);
insert into author_book (author_id, book_id) values (57, 94);
insert into author_book (author_id, book_id) values (67, 34);
insert into author_book (author_id, book_id) values (19, 95);
insert into author_book (author_id, book_id) values (6, 10);
insert into author_book (author_id, book_id) values (87, 80);
insert into author_book (author_id, book_id) values (35, 79);
insert into author_book (author_id, book_id) values (36, 76);
insert into author_book (author_id, book_id) values (57, 55);
insert into author_book (author_id, book_id) values (17, 90);
insert into author_book (author_id, book_id) values (100, 50);
insert into author_book (author_id, book_id) values (32, 12);
insert into author_book (author_id, book_id) values (2, 48);
insert into author_book (author_id, book_id) values (98, 91);
insert into author_book (author_id, book_id) values (90, 92);
insert into author_book (author_id, book_id) values (12, 34);
insert into author_book (author_id, book_id) values (80, 44);
insert into author_book (author_id, book_id) values (17, 32);
insert into author_book (author_id, book_id) values (32, 6);
insert into author_book (author_id, book_id) values (67, 54);
insert into author_book (author_id, book_id) values (18, 7);
insert into author_book (author_id, book_id) values (54, 94);
insert into author_book (author_id, book_id) values (17, 26);
insert into author_book (author_id, book_id) values (70, 82);
insert into author_book (author_id, book_id) values (2, 95);
insert into author_book (author_id, book_id) values (31, 37);
insert into author_book (author_id, book_id) values (10, 91);
insert into author_book (author_id, book_id) values (52, 30);
insert into author_book (author_id, book_id) values (53, 60);
insert into author_book (author_id, book_id) values (58, 83);
insert into author_book (author_id, book_id) values (27, 20);
insert into author_book (author_id, book_id) values (9, 92);
insert into author_book (author_id, book_id) values (85, 14);
insert into author_book (author_id, book_id) values (56, 99);
insert into author_book (author_id, book_id) values (57, 52);
insert into author_book (author_id, book_id) values (4, 55);
insert into author_book (author_id, book_id) values (61, 97);
insert into author_book (author_id, book_id) values (67, 45);
insert into author_book (author_id, book_id) values (84, 44);
insert into author_book (author_id, book_id) values (90, 96);
insert into author_book (author_id, book_id) values (57, 5);
insert into author_book (author_id, book_id) values (10, 23);
insert into author_book (author_id, book_id) values (100, 84);
insert into author_book (author_id, book_id) values (52, 41);
insert into author_book (author_id, book_id) values (16, 83);
insert into author_book (author_id, book_id) values (49, 65);
insert into author_book (author_id, book_id) values (19, 16);
insert into author_book (author_id, book_id) values (42, 49);
insert into author_book (author_id, book_id) values (83, 83);
insert into author_book (author_id, book_id) values (75, 93);
insert into author_book (author_id, book_id) values (8, 7);
insert into author_book (author_id, book_id) values (26, 47);
insert into author_book (author_id, book_id) values (38, 19);
insert into author_book (author_id, book_id) values (29, 44);
insert into author_book (author_id, book_id) values (68, 40);
insert into author_book (author_id, book_id) values (29, 94);
insert into author_book (author_id, book_id) values (44, 2);
insert into author_book (author_id, book_id) values (55, 19);
insert into author_book (author_id, book_id) values (8, 63);
insert into author_book (author_id, book_id) values (11, 97);
insert into author_book (author_id, book_id) values (87, 39);
insert into author_book (author_id, book_id) values (69, 72);
insert into author_book (author_id, book_id) values (93, 4);
insert into author_book (author_id, book_id) values (74, 70);
insert into author_book (author_id, book_id) values (68, 48);
insert into author_book (author_id, book_id) values (49, 35);
insert into author_book (author_id, book_id) values (85, 49);
insert into author_book (author_id, book_id) values (98, 8);
insert into author_book (author_id, book_id) values (98, 5);
insert into author_book (author_id, book_id) values (88, 78);
insert into author_book (author_id, book_id) values (50, 67);
insert into author_book (author_id, book_id) values (45, 81);
insert into author_book (author_id, book_id) values (14, 59);
insert into author_book (author_id, book_id) values (55, 5);
insert into author_book (author_id, book_id) values (96, 91);
insert into author_book (author_id, book_id) values (14, 30);
insert into author_book (author_id, book_id) values (53, 39);
insert into author_book (author_id, book_id) values (2, 43);
insert into author_book (author_id, book_id) values (79, 90);
insert into author_book (author_id, book_id) values (92, 68);
insert into author_book (author_id, book_id) values (51, 1);
insert into author_book (author_id, book_id) values (93, 51);
insert into author_book (author_id, book_id) values (14, 40);
insert into author_book (author_id, book_id) values (27, 60);
insert into author_book (author_id, book_id) values (1, 37);
