insert into author (age, name, genre) values (26, 'Nelie', 'action');
insert into author (age, name, genre) values (25, 'Ku', 'romance');
insert into author (age, name, genre) values (33, 'Po', 'action');
insert into author (age, name, genre) values (36, 'Laurena', 'action');
insert into author (age, name, genre) values (27, 'Clemence', 'thriller');
insert into author (age, name, genre) values (32, 'Desiree', 'comedy');
insert into author (age, name, genre) values (39, 'Amelie', 'drama');
insert into author (age, name, genre) values (39, 'Adelie', 'comedy');
insert into author (age, name, genre) values (32, 'Anaelle', 'action');
insert into author (age, name, genre) values (40, 'Maelyss', 'romance');
insert into author (age, name, genre) values (38, 'Marie-therese', 'romance');
insert into author (age, name, genre) values (37, 'Gerald', 'drama');
insert into author (age, name, genre) values (29, 'Yú', 'comedy');
insert into author (age, name, genre) values (38, 'Angele', 'thriller');
insert into author (age, name, genre) values (31, 'Loic', 'romance');
insert into author (age, name, genre) values (30, 'Nadege', 'drama');
insert into author (age, name, genre) values (26, 'Esteve', 'action');
insert into author (age, name, genre) values (33, 'Creez', 'action');
insert into author (age, name, genre) values (39, 'Pow', 'drama');
insert into author (age, name, genre) values (27, 'Neliean', 'thriller');


insert into publisher (company) values ('Katz');
insert into publisher (company) values ('Oyondu');
insert into publisher (company) values ('Leenti');
insert into publisher (company) values ('Dynazzy');
insert into publisher (company) values ('Devshare');
insert into publisher (company) values ('Skinix');
insert into publisher (company) values ('Buzzster');
insert into publisher (company) values ('Cogilith');
insert into publisher (company) values ('Rhybox');
insert into publisher (company) values ('Edgeblab');


insert into book (isbn, title, author_id, publisher_id) values ('700977808-6', 'Naked', 13, 1);
insert into book (isbn, title, author_id, publisher_id) values ('729247656-2', 'Arrowhead', 1, 7);
insert into book (isbn, title, author_id, publisher_id) values ('890422356-3', 'Lapland Odyssey (Napapiirin sankarit)', 1, 10);
insert into book (isbn, title, author_id, publisher_id) values ('406071857-2', 'Equinox', 18, 7);
insert into book (isbn, title, author_id, publisher_id) values ('053141060-9', 'La cravate', 3, 5);
insert into book (isbn, title, author_id, publisher_id) values ('007940154-6', 'Librarian: Return to King Solomon''s Mines, The', 6, 6);
insert into book (isbn, title, author_id, publisher_id) values ('410245960-X', 'River of No Return', 15, 1);
insert into book (isbn, title, author_id, publisher_id) values ('837188320-X', 'Quest for Camelot', 9, 4);
insert into book (isbn, title, author_id, publisher_id) values ('989411567-5', 'No End in Sight', 15, 8);
insert into book (isbn, title, author_id, publisher_id) values ('045980752-8', 'Pom Poko (a.k.a. Raccoon War, The) (Heisei tanuki gassen pompoko)', 19, 10);
insert into book (isbn, title, author_id, publisher_id) values ('775833921-2', 'Divine Intervention (Yadon ilaheyya)', 15, 5);
insert into book (isbn, title, author_id, publisher_id) values ('100439474-8', 'Lammbock', 5, 1);
insert into book (isbn, title, author_id, publisher_id) values ('215940742-9', 'Jonestown: The Life and Death of Peoples Temple', 1, 7);
insert into book (isbn, title, author_id, publisher_id) values ('919976043-6', 'Contender, The', 8, 4);
insert into book (isbn, title, author_id, publisher_id) values ('310483966-2', 'Jesse Stone: Benefit of the Doubt', 11, 10);
insert into book (isbn, title, author_id, publisher_id) values ('330441146-1', 'Late Mathias Pascal, The (a.k.a. The Living Dead Man) (Feu Mathias Pascal)', 9, 4);
insert into book (isbn, title, author_id, publisher_id) values ('796008464-5', 'Ali Zoua: Prince of the Streets (Ali Zaoua, prince de la rue)', 13, 6);
insert into book (isbn, title, author_id, publisher_id) values ('653002184-1', 'Dot the I', 5, 10);
insert into book (isbn, title, author_id, publisher_id) values ('390379712-X', 'Rain', 8, 8);
insert into book (isbn, title, author_id, publisher_id) values ('015905020-0', 'Mirage', 20, 1);
insert into book (isbn, title, author_id, publisher_id) values ('596389395-X', 'Shark Skin Man and Peach Hip Girl (Samehada otoko to momojiri onna)', 1, 6);
insert into book (isbn, title, author_id, publisher_id) values ('759599294-X', '8 Seconds', 16, 5);
insert into book (isbn, title, author_id, publisher_id) values ('904999322-2', 'White Bird in a Blizzard', 10, 9);
insert into book (isbn, title, author_id, publisher_id) values ('244673797-8', 'Han Gong-ju', 9, 4);
insert into book (isbn, title, author_id, publisher_id) values ('477304870-0', 'Broken Arrow', 3, 4);
insert into book (isbn, title, author_id, publisher_id) values ('763704479-3', 'Home from the Hill', 6, 10);
insert into book (isbn, title, author_id, publisher_id) values ('372486479-5', 'Tell', 12, 3);
insert into book (isbn, title, author_id, publisher_id) values ('547422722-1', 'Hills Have Eyes II, The', 7, 9);
insert into book (isbn, title, author_id, publisher_id) values ('784181762-2', 'Modulations', 19, 6);
insert into book (isbn, title, author_id, publisher_id) values ('884370169-X', 'Gold Diggers of 1933', 10, 6);
insert into book (isbn, title, author_id, publisher_id) values ('997062637-X', 'Withnail & I', 1, 8);
insert into book (isbn, title, author_id, publisher_id) values ('573120325-3', 'Sidekicks', 5, 7);
insert into book (isbn, title, author_id, publisher_id) values ('744636223-5', 'Redline', 13, 1);
insert into book (isbn, title, author_id, publisher_id) values ('912294141-X', 'Jim Gaffigan: Obsessed', 16, 1);
insert into book (isbn, title, author_id, publisher_id) values ('070160600-2', 'Knight and Day', 17, 5);
insert into book (isbn, title, author_id, publisher_id) values ('091745641-6', 'Me and Earl and the Dying Girl', 3, 5);
insert into book (isbn, title, author_id, publisher_id) values ('098515285-0', 'Chaperone, The', 9, 8);
insert into book (isbn, title, author_id, publisher_id) values ('980153945-3', 'Monty Python''s And Now for Something Completely Different', 2, 7);
insert into book (isbn, title, author_id, publisher_id) values ('050904881-1', 'Branded', 14, 8);
insert into book (isbn, title, author_id, publisher_id) values ('316525645-4', 'Withnail & I', 10, 1);
insert into book (isbn, title, author_id, publisher_id) values ('077511998-9', 'American Zombie', 5, 6);
insert into book (isbn, title, author_id, publisher_id) values ('180254670-7', 'Fruitvale Station', 1, 8);
insert into book (isbn, title, author_id, publisher_id) values ('141539988-3', 'Descendants, The', 6, 4);
insert into book (isbn, title, author_id, publisher_id) values ('997094855-5', 'Diva', 11, 9);
insert into book (isbn, title, author_id, publisher_id) values ('007746489-3', 'Double Tide', 20, 4);
insert into book (isbn, title, author_id, publisher_id) values ('273833669-8', 'Grocer''s Son, The (Fils de l''épicier, Le)', 10, 6);
insert into book (isbn, title, author_id, publisher_id) values ('331685863-6', 'Kumiko, the Treasure Hunter', 5, 1);
insert into book (isbn, title, author_id, publisher_id) values ('216715700-2', 'Koumiko Mystery, The (Mystère Koumiko, Le)', 15, 1);
insert into book (isbn, title, author_id, publisher_id) values ('196202461-X', 'If These Walls Could Talk', 14, 10);
insert into book (isbn, title, author_id, publisher_id) values ('145625345-X', 'Adam & Steve', 20, 3);
insert into book (isbn, title, author_id, publisher_id) values ('209694951-3', 'The Dot and the Line : A Romance in Lower Mathematics', 2, 4);
insert into book (isbn, title, author_id, publisher_id) values ('780069738-X', 'Monster in the Closet', 10, 10);
insert into book (isbn, title, author_id, publisher_id) values ('866340616-9', 'The Boys', 15, 7);
insert into book (isbn, title, author_id, publisher_id) values ('819200734-0', 'Phyllis and Harold', 15, 4);
insert into book (isbn, title, author_id, publisher_id) values ('969145019-4', 'Miracle at Oxford (True Blue)', 7, 9);
insert into book (isbn, title, author_id, publisher_id) values ('977179449-3', 'Fog of War: Eleven Lessons from the Life of Robert S. McNamara, The', 2, 3);
insert into book (isbn, title, author_id, publisher_id) values ('155047621-1', 'Seance on a Wet Afternoon', 13, 7);
insert into book (isbn, title, author_id, publisher_id) values ('455358756-4', 'Satan Met a Lady', 10, 2);
insert into book (isbn, title, author_id, publisher_id) values ('898412969-0', 'Zaat', 11, 8);
insert into book (isbn, title, author_id, publisher_id) values ('204114215-4', 'Substance of Fire, The', 4, 10);
insert into book (isbn, title, author_id, publisher_id) values ('721080153-7', 'Idlewild', 2, 10);
insert into book (isbn, title, author_id, publisher_id) values ('108981332-5', 'Owning Mahowny', 2, 9);
insert into book (isbn, title, author_id, publisher_id) values ('829917861-4', 'Big Wednesday', 8, 7);
insert into book (isbn, title, author_id, publisher_id) values ('586203167-7', 'Theory of Flight, The', 2, 7);
insert into book (isbn, title, author_id, publisher_id) values ('251018493-8', 'Reefer Madness: The Movie Musical', 6, 1);
insert into book (isbn, title, author_id, publisher_id) values ('654697026-0', 'City Slickers II: The Legend of Curly''s Gold', 10, 4);
insert into book (isbn, title, author_id, publisher_id) values ('460625112-3', 'Mickey, Donald, Goofy: The Three Musketeers', 2, 8);
insert into book (isbn, title, author_id, publisher_id) values ('539180278-4', 'Patriot Games', 2, 9);
insert into book (isbn, title, author_id, publisher_id) values ('484835702-0', 'Subspecies', 14, 6);
insert into book (isbn, title, author_id, publisher_id) values ('204636762-6', 'Thunderbird Six', 3, 5);
insert into book (isbn, title, author_id, publisher_id) values ('631917594-X', 'Last Seduction, The', 11, 7);
insert into book (isbn, title, author_id, publisher_id) values ('179585156-2', 'Kurt Cobain About a Son', 10, 3);
insert into book (isbn, title, author_id, publisher_id) values ('733375762-5', 'Price of Forgiveness, The (Ndeysaan)', 2, 6);
insert into book (isbn, title, author_id, publisher_id) values ('854036900-1', 'Fire of Conscience (For lung)', 4, 10);
insert into book (isbn, title, author_id, publisher_id) values ('629381985-3', 'Alaska', 11, 4);
insert into book (isbn, title, author_id, publisher_id) values ('178947585-6', 'Bishop Murder Case, The', 4, 10);
insert into book (isbn, title, author_id, publisher_id) values ('428743982-1', 'Rich Man''s Wife, The', 7, 6);
insert into book (isbn, title, author_id, publisher_id) values ('243192880-2', 'Category 7: The End of the World', 4, 5);
insert into book (isbn, title, author_id, publisher_id) values ('964041641-X', 'Broadway', 20, 1);
insert into book (isbn, title, author_id, publisher_id) values ('125293368-1', 'Dark, The', 9, 9);
insert into book (isbn, title, author_id, publisher_id) values ('638040026-5', 'Hurt', 17, 1);
insert into book (isbn, title, author_id, publisher_id) values ('847579501-3', 'Listy do M.', 17, 7);
insert into book (isbn, title, author_id, publisher_id) values ('957488402-3', 'Deliver Us from Evil', 9, 5);
insert into book (isbn, title, author_id, publisher_id) values ('583483803-0', 'Chillerama', 9, 8);
insert into book (isbn, title, author_id, publisher_id) values ('957302129-3', 'In the Fog (V tumane)', 6, 2);
insert into book (isbn, title, author_id, publisher_id) values ('126075458-8', 'Samoure', 16, 6);
insert into book (isbn, title, author_id, publisher_id) values ('396627789-1', 'Absolute Aggression', 12, 5);
insert into book (isbn, title, author_id, publisher_id) values ('864681310-X', 'In Your Hands (Forbrydelser)', 8, 8);
insert into book (isbn, title, author_id, publisher_id) values ('422900747-7', 'Go', 15, 3);
insert into book (isbn, title, author_id, publisher_id) values ('216486830-7', 'The Coven', 6, 8);
insert into book (isbn, title, author_id, publisher_id) values ('331581786-3', 'Mr. Woodcock', 9, 5);
insert into book (isbn, title, author_id, publisher_id) values ('901610978-1', 'Borderline', 7, 6);
insert into book (isbn, title, author_id, publisher_id) values ('091126119-2', 'Loser Takes All! (Qui perd gagne !)', 19, 6);
insert into book (isbn, title, author_id, publisher_id) values ('477258838-8', 'Deck the Halls', 12, 7);
insert into book (isbn, title, author_id, publisher_id) values ('961953890-0', 'The Inhabited Island', 2, 4);
insert into book (isbn, title, author_id, publisher_id) values ('953909669-3', 'Glenn Killing på Berns', 16, 5);
insert into book (isbn, title, author_id, publisher_id) values ('825768346-9', 'Zombie Strippers!', 4, 1);
insert into book (isbn, title, author_id, publisher_id) values ('961083881-2', 'Opfergang', 3, 6);
insert into book (isbn, title, author_id, publisher_id) values ('636687850-1', 'Out of the Fog', 14, 7);
insert into book (isbn, title, author_id, publisher_id) values ('362883298-5', 'Scourge', 3, 2);