insert into author (age, name, genre, email, address, rating) values (24, 'Berty', 'drama', 'bswateridge0@elpais.com', 'Wailolung', 68);
insert into author (age, name, genre, email, address, rating) values (24, 'Dosi', 'romance', 'dhalward1@desdev.cn', 'Sabanagrande', 18);
insert into author (age, name, genre, email, address, rating) values (48, 'Rosalynd', 'drama', 'rhardypiggin2@meetup.com', 'Bella Vista', 51);
insert into author (age, name, genre, email, address, rating) values (59, 'Cleon', 'horror', 'cdrezzer3@skype.com', 'San Teodoro', 52);
insert into author (age, name, genre, email, address, rating) values (43, 'Flori', 'romance', 'fobradden4@sfgate.com', 'Raci Kulon', 59);
insert into author (age, name, genre, email, address, rating) values (32, 'Genny', 'action', 'ggodfrey5@wordpress.org', 'Kongjiafang', 38);
insert into author (age, name, genre, email, address, rating) values (43, 'Fanni', 'drama', 'fsilverman6@chronoengine.com', 'San Jose', 44);
insert into author (age, name, genre, email, address, rating) values (48, 'Marlyn', 'romance', 'msiddell7@fotki.com', 'Sandur', 52);
insert into author (age, name, genre, email, address, rating) values (63, 'Hammad', 'drama', 'hhinken8@dyndns.org', 'Palaiseau', 51);
insert into author (age, name, genre, email, address, rating) values (25, 'Averyl', 'action', 'adeeson9@soup.io', 'Haenam', 100);
insert into author (age, name, genre, email, address, rating) values (59, 'Phillipp', 'comedy', 'pmatthiaea@dailymotion.com', 'Onega', 28);
insert into author (age, name, genre, email, address, rating) values (65, 'Shepperd', 'action', 'sosanb@live.com', 'Ŭiju', 10);
insert into author (age, name, genre, email, address, rating) values (37, 'Filippa', 'action', 'farthursc@tuttocitta.it', 'Dafeng', 66);
insert into author (age, name, genre, email, address, rating) values (58, 'Ashton', 'romance', 'aridwoodd@geocities.jp', 'San Miguel', 12);
insert into author (age, name, genre, email, address, rating) values (34, 'Morganica', 'romance', 'mallawaye@weibo.com', 'Huerta Grande', 28);
insert into author (age, name, genre, email, address, rating) values (27, 'Sergent', 'comedy', 'shughsf@is.gd', 'Saint-Étienne', 72);
insert into author (age, name, genre, email, address, rating) values (33, 'Stu', 'drama', 'stieraneyg@huffingtonpost.com', 'Mortka', 24);
insert into author (age, name, genre, email, address, rating) values (59, 'Yale', 'drama', 'yreddingh@freewebs.com', 'Sant Julià de Lòria', 29);
insert into author (age, name, genre, email, address, rating) values (46, 'Staford', 'romance', 'sbunyani@friendfeed.com', 'Yanghu', 16);
insert into author (age, name, genre, email, address, rating) values (51, 'Renado', 'comedy', 'reirwinj@merriam-webster.com', 'Shah Alam', 31);
insert into author (age, name, genre, email, address, rating) values (43, 'Minor', 'drama', 'mseddonk@deviantart.com', 'Rosh Ha‘Ayin', 62);
insert into author (age, name, genre, email, address, rating) values (53, 'Joachim', 'horror', 'jtwohigl@irs.gov', 'Tarumizu', 58);
insert into author (age, name, genre, email, address, rating) values (37, 'Audrye', 'drama', 'atennickm@purevolume.com', 'Wuyang', 20);
insert into author (age, name, genre, email, address, rating) values (56, 'Isadora', 'romance', 'ilevyn@dedecms.com', 'Ayaviri', 44);
insert into author (age, name, genre, email, address, rating) values (54, 'Brande', 'drama', 'bandriveauxo@moonfruit.com', 'Nahrīn', 96);
insert into author (age, name, genre, email, address, rating) values (20, 'Rob', 'drama', 'rdietschep@surveymonkey.com', 'Ilha Solteira', 95);
insert into author (age, name, genre, email, address, rating) values (45, 'Ulrick', 'romance', 'ureinbachq@google.com.br', 'Novouzensk', 14);
insert into author (age, name, genre, email, address, rating) values (25, 'Augusta', 'horror', 'alowerr@ehow.com', 'Itororó', 85);
insert into author (age, name, genre, email, address, rating) values (45, 'Maximo', 'drama', 'mgounys@kickstarter.com', 'Allealle', 18);
insert into author (age, name, genre, email, address, rating) values (54, 'Simon', 'drama', 'sgrigoryovt@hostgator.com', 'Dhromolaxia', 68);
insert into author (age, name, genre, email, address, rating) values (30, 'Rinaldo', 'horror', 'rdumbltonu@sphinn.com', 'Inglewood', 52);
insert into author (age, name, genre, email, address, rating) values (21, 'Donnie', 'romance', 'dmourtonv@nytimes.com', 'Radomin', 52);
insert into author (age, name, genre, email, address, rating) values (40, 'Mallory', 'horror', 'mmocquerw@indiegogo.com', 'Radomin', 44);
insert into author (age, name, genre, email, address, rating) values (51, 'Kimmy', 'romance', 'kkopecx@facebook.com', 'Primorsko-Akhtarsk', 40);
insert into author (age, name, genre, email, address, rating) values (35, 'Egor', 'drama', 'eorrissy@wikimedia.org', 'Pukou', 38);
insert into author (age, name, genre, email, address, rating) values (65, 'Mercie', 'drama', 'mlovatz@ning.com', 'Orlu', 36);
insert into author (age, name, genre, email, address, rating) values (65, 'Gina', 'drama', 'ghammond10@sun.com', 'Lagoaça', 25);
insert into author (age, name, genre, email, address, rating) values (46, 'Quintina', 'comedy', 'qscoggans11@adobe.com', 'Angoulême', 50);
insert into author (age, name, genre, email, address, rating) values (52, 'Shaylah', 'romance', 'smcinnery12@ucoz.com', 'Ushiku', 99);
insert into author (age, name, genre, email, address, rating) values (49, 'Melamie', 'romance', 'mwishkar13@jugem.jp', 'Kunda', 14);
insert into author (age, name, genre, email, address, rating) values (44, 'Darb', 'horror', 'dearles14@wikimedia.org', 'Rontu', 84);
insert into author (age, name, genre, email, address, rating) values (34, 'Loralyn', 'horror', 'lmacdougall15@freewebs.com', 'Machinga', 3);
insert into author (age, name, genre, email, address, rating) values (38, 'Herta', 'comedy', 'hexon16@sfgate.com', 'Odemira', 64);
insert into author (age, name, genre, email, address, rating) values (35, 'Alfred', 'drama', 'aubsdale17@europa.eu', 'Al Qūşīyah', 83);
insert into author (age, name, genre, email, address, rating) values (25, 'Aline', 'action', 'acranage18@squarespace.com', 'Matmata', 82);
insert into author (age, name, genre, email, address, rating) values (55, 'Mathias', 'comedy', 'mroberto19@jimdo.com', 'Yuyapichis', 1);
insert into author (age, name, genre, email, address, rating) values (37, 'Wells', 'comedy', 'wpaine1a@discovery.com', 'Fos-sur-Mer', 49);
insert into author (age, name, genre, email, address, rating) values (44, 'Ulrika', 'drama', 'uwinman1b@ameblo.jp', 'San Antonio', 34);
insert into author (age, name, genre, email, address, rating) values (33, 'Rasla', 'horror', 'rboor1c@mozilla.com', 'Póvoa de Santo António', 26);
insert into author (age, name, genre, email, address, rating) values (34, 'Athena', 'horror', 'adales1d@last.fm', 'Gungguh', 79);
insert into author (age, name, genre, email, address, rating) values (25, 'Lissy', 'action', 'lbeccles1e@mail.ru', 'Serra da Boa Viagem', 53);
insert into author (age, name, genre, email, address, rating) values (61, 'Scotti', 'horror', 'sduguid1f@shareasale.com', 'Corpus Christi', 50);
insert into author (age, name, genre, email, address, rating) values (29, 'Winston', 'horror', 'wbarsby1g@google.de', 'Migues', 13);
insert into author (age, name, genre, email, address, rating) values (30, 'Jacquelin', 'comedy', 'jjone1h@blogspot.com', 'Ţāqchah Khānah', 28);
insert into author (age, name, genre, email, address, rating) values (44, 'Noell', 'romance', 'nengeham1i@dyndns.org', 'Nirasaki', 56);
insert into author (age, name, genre, email, address, rating) values (40, 'Corine', 'horror', 'charget1j@facebook.com', 'Blagoevgrad', 77);
insert into author (age, name, genre, email, address, rating) values (20, 'Trefor', 'romance', 'tgallgher1k@narod.ru', 'Lingzhi', 90);
insert into author (age, name, genre, email, address, rating) values (40, 'Malchy', 'romance', 'manderbrugge1l@etsy.com', 'Ghouazi', 28);
insert into author (age, name, genre, email, address, rating) values (28, 'Eachelle', 'drama', 'edearl1m@cbslocal.com', 'Libertador General San Martín', 83);
insert into author (age, name, genre, email, address, rating) values (65, 'Winna', 'romance', 'wleonardi1n@homestead.com', 'Tangping', 8);
insert into author (age, name, genre, email, address, rating) values (22, 'Caldwell', 'action', 'csheryne1o@accuweather.com', 'Kolbuszowa', 97);
insert into author (age, name, genre, email, address, rating) values (34, 'Amby', 'drama', 'abroun1p@aol.com', 'Raas', 57);
insert into author (age, name, genre, email, address, rating) values (60, 'Osgood', 'action', 'obriat1q@bluehost.com', 'Nagarakembang', 6);
insert into author (age, name, genre, email, address, rating) values (32, 'Linus', 'drama', 'lstappard1r@exblog.jp', 'Zhuxi Chengguanzhen', 98);
insert into author (age, name, genre, email, address, rating) values (32, 'Isador', 'action', 'ilowry1s@census.gov', 'Santo Antônio de Pádua', 96);
insert into author (age, name, genre, email, address, rating) values (63, 'Lemmy', 'romance', 'lcapes1t@opera.com', 'Sang-e Chārak', 52);
insert into author (age, name, genre, email, address, rating) values (27, 'Dalli', 'drama', 'dbarlace1u@nhs.uk', 'Ngilengan', 66);
insert into author (age, name, genre, email, address, rating) values (22, 'Trixi', 'drama', 'tfortune1v@ucoz.com', 'Karangmangu', 19);
insert into author (age, name, genre, email, address, rating) values (65, 'Jourdan', 'drama', 'jeddolls1w@google.it', 'Krajansumbermujur', 77);
insert into author (age, name, genre, email, address, rating) values (65, 'Anya', 'horror', 'aandrat1x@webeden.co.uk', 'Jaguariaíva', 32);
insert into author (age, name, genre, email, address, rating) values (44, 'Gino', 'drama', 'gsharple1y@reuters.com', 'Al Kiswah', 79);
insert into author (age, name, genre, email, address, rating) values (64, 'Dollie', 'comedy', 'dmarkey1z@berkeley.edu', 'Dananshan', 68);
insert into author (age, name, genre, email, address, rating) values (49, 'Leann', 'comedy', 'lrea20@businessweek.com', 'Tan Sum', 23);
insert into author (age, name, genre, email, address, rating) values (28, 'Sydney', 'romance', 'sdobbyn21@pcworld.com', 'Plasy', 45);
insert into author (age, name, genre, email, address, rating) values (49, 'Stepha', 'comedy', 'slewry22@cafepress.com', 'Vyritsa', 21);
insert into author (age, name, genre, email, address, rating) values (22, 'Kimberlyn', 'comedy', 'kstillmann23@ycombinator.com', 'Onitsha', 4);
insert into author (age, name, genre, email, address, rating) values (20, 'Netti', 'action', 'nbryer24@delicious.com', 'Shuren', 85);
insert into author (age, name, genre, email, address, rating) values (21, 'Conrade', 'drama', 'cbootton25@hubpages.com', 'Błonie', 15);
insert into author (age, name, genre, email, address, rating) values (21, 'Robby', 'comedy', 'rmacgeaney26@nhs.uk', 'Niutian', 9);
insert into author (age, name, genre, email, address, rating) values (26, 'Cammy', 'comedy', 'crault27@dropbox.com', 'Srostki', 94);
insert into author (age, name, genre, email, address, rating) values (24, 'Tim', 'drama', 'tvasyutkin28@rediff.com', 'Toulouse', 9);
insert into author (age, name, genre, email, address, rating) values (30, 'Deeyn', 'action', 'davrahamoff29@seattletimes.com', 'Białobrzegi', 24);
insert into author (age, name, genre, email, address, rating) values (34, 'Rutter', 'comedy', 'rmarshallsay2a@sogou.com', 'La Condamine', 61);
insert into author (age, name, genre, email, address, rating) values (60, 'Malia', 'action', 'mhaylock2b@army.mil', 'Strogino', 14);
insert into author (age, name, genre, email, address, rating) values (34, 'Pip', 'action', 'progerson2c@twitpic.com', 'Mós', 24);
insert into author (age, name, genre, email, address, rating) values (57, 'Ginni', 'action', 'gtommasuzzi2d@blogs.com', 'Siemiechów', 10);
insert into author (age, name, genre, email, address, rating) values (62, 'Vina', 'comedy', 'vmartin2e@constantcontact.com', 'Albany', 54);
insert into author (age, name, genre, email, address, rating) values (46, 'Inglis', 'comedy', 'ispeere2f@goo.gl', 'Oganlima', 54);
insert into author (age, name, genre, email, address, rating) values (55, 'Nilson', 'action', 'ntrustey2g@t-online.de', 'Ilek', 95);
insert into author (age, name, genre, email, address, rating) values (61, 'Mozelle', 'drama', 'mgaber2h@storify.com', 'Néa Kíos', 70);
insert into author (age, name, genre, email, address, rating) values (31, 'Pen', 'drama', 'prewcassell2i@xrea.com', 'Tabiauan', 11);
insert into author (age, name, genre, email, address, rating) values (51, 'Annetta', 'romance', 'ajewis2j@comsenz.com', 'Bastia', 81);
insert into author (age, name, genre, email, address, rating) values (27, 'Elizabet', 'comedy', 'eboyne2k@nytimes.com', 'Aguisan', 39);
insert into author (age, name, genre, email, address, rating) values (55, 'Web', 'action', 'wgroom2l@umn.edu', 'Baizhu', 34);
insert into author (age, name, genre, email, address, rating) values (37, 'Maryjo', 'horror', 'mdumbellow2m@businesswire.com', 'Kasamatsuchō', 41);
insert into author (age, name, genre, email, address, rating) values (59, 'Kalvin', 'action', 'kwestphalen2n@scientificamerican.com', 'Lannion', 4);
insert into author (age, name, genre, email, address, rating) values (27, 'Judi', 'drama', 'jborg2o@cargocollective.com', 'Spárti', 52);
insert into author (age, name, genre, email, address, rating) values (32, 'Virgil', 'horror', 'vbrandt2p@chron.com', 'Bashan', 58);
insert into author (age, name, genre, email, address, rating) values (29, 'Mel', 'horror', 'msighart2q@com.com', 'Igarapé', 94);
insert into author (age, name, genre, email, address, rating) values (34, 'Blondelle', 'romance', 'bcamamile2r@mac.com', 'Taganak', 43);
