insert into author (age, name, genre) values (20, 'Hatty', 'romance');
insert into author (age, name, genre) values (41, 'Cyril', 'romance');
insert into author (age, name, genre) values (46, 'Stefan', 'comedy');
insert into author (age, name, genre) values (59, 'Franky', 'horror');
insert into author (age, name, genre) values (23, 'Garreth', 'action');
insert into author (age, name, genre) values (34, 'Lianne', 'drama');
insert into author (age, name, genre) values (44, 'Ede', 'comedy');
insert into author (age, name, genre) values (61, 'Annamaria', 'drama');
insert into author (age, name, genre) values (54, 'Tildi', 'drama');
insert into author (age, name, genre) values (33, 'Chicky', 'horror');
insert into author (age, name, genre) values (63, 'Martainn', 'romance');
insert into author (age, name, genre) values (31, 'Marius', 'action');
insert into author (age, name, genre) values (35, 'Tiler', 'romance');
insert into author (age, name, genre) values (41, 'Laurene', 'drama');
insert into author (age, name, genre) values (58, 'Sheela', 'action');
insert into author (age, name, genre) values (43, 'Vern', 'drama');
insert into author (age, name, genre) values (64, 'Rebbecca', 'drama');
insert into author (age, name, genre) values (56, 'Axe', 'action');
insert into author (age, name, genre) values (57, 'Sheba', 'horror');
insert into author (age, name, genre) values (28, 'Gris', 'horror');


insert into book (title, price) values ('Kevin Smith: Too Fat For 40', 31);
insert into book (title, price) values ('Warriors of Heaven and Earth (Tian di ying xiong)', 16);
insert into book (title, price) values ('Our Paradise (Notre paradis)', 37);
insert into book (title, price) values ('Lilian''s Story', 18);
insert into book (title, price) values ('All American Orgy (Cummings Farm)', 23);
insert into book (title, price) values ('Island of Dr. Moreau, The', 46);
insert into book (title, price) values ('Das Leben ist nichts für Feiglinge', 32);
insert into book (title, price) values ('Morning of the Earth', 15);
insert into book (title, price) values ('All the Queen''s Men', 13);
insert into book (title, price) values ('An American Hippie in Israel', 49);
insert into book (title, price) values ('3-Iron (Bin-jip)', 23);
insert into book (title, price) values ('Kid in King Arthur''s Court, A', 16);
insert into book (title, price) values ('Godzilla vs. Megaguirus (Gojira tai Megagirasu: Jî shômetsu sakusen)', 27);
insert into book (title, price) values ('Mr. Blandings Builds His Dream House', 26);
insert into book (title, price) values ('Four Eyes and Six-Guns', 23);
insert into book (title, price) values ('American Wedding (American Pie 3)', 26);
insert into book (title, price) values ('Lathe of Heaven, The', 19);
insert into book (title, price) values ('Saving God', 25);
insert into book (title, price) values ('Camelot', 44);
insert into book (title, price) values ('Twentynine Palms', 34);
insert into book (title, price) values ('Last September, The', 11);
insert into book (title, price) values ('Angels Over Broadway', 24);
insert into book (title, price) values ('Vic+Flo Saw a Bear', 36);
insert into book (title, price) values ('28 Days Later', 22);
insert into book (title, price) values ('Law Abiding Citizen', 22);
insert into book (title, price) values ('Shadow Boxers', 28);
insert into book (title, price) values ('Dirties, The', 14);
insert into book (title, price) values ('Cider House Rules, The', 36);
insert into book (title, price) values ('Genocide', 35);
insert into book (title, price) values ('Louis Theroux: Twilight of the Porn Stars', 47);
insert into book (title, price) values ('Anna Karenina', 35);
insert into book (title, price) values ('From Up on Poppy Hill (Kokuriko-zaka kara)', 25);
insert into book (title, price) values ('Léon: The Professional (a.k.a. The Professional) (Léon)', 40);
insert into book (title, price) values ('Shakespeare-Wallah', 34);
insert into book (title, price) values ('Street Thief', 21);
insert into book (title, price) values ('I Want to Look Like That Guy', 33);
insert into book (title, price) values ('Physical Evidence', 22);
insert into book (title, price) values ('Slaughterhouse-Five', 34);
insert into book (title, price) values ('Shine a Light', 12);
insert into book (title, price) values ('Unknown Soldier, The (Tuntematon sotilas)', 50);
insert into book (title, price) values ('Torque', 41);
insert into book (title, price) values ('Gone to Earth', 35);
insert into book (title, price) values ('Kabluey', 19);
insert into book (title, price) values ('For Love and Gold (L''armata Brancaleone)', 28);
insert into book (title, price) values ('Love Affair, or the Case of the Missing Switchboard Operator (Ljubavni slucaj ili tragedija sluzbenice P.T.T.)', 22);
insert into book (title, price) values ('Severance', 27);
insert into book (title, price) values ('SSSSSSS', 20);
insert into book (title, price) values ('Avenging Conscience, The', 45);
insert into book (title, price) values ('Gospel According to St. Matthew, The (Vangelo secondo Matteo, Il)', 30);
insert into book (title, price) values ('Uncommon Valor', 40);
insert into book (title, price) values ('Sunrise: A Song of Two Humans', 16);
insert into book (title, price) values ('Silent Action', 26);
insert into book (title, price) values ('Television Under the Swastika (Das Fernsehen unter dem Hakenkreuz)', 32);
insert into book (title, price) values ('Latitude Zero (Ido zero daisakusen)', 36);
insert into book (title, price) values ('First Blood (Rambo: First Blood)', 47);
insert into book (title, price) values ('When Darkness Falls (När mörkret faller)', 11);
insert into book (title, price) values ('Kingdom, The (Riget)', 47);
insert into book (title, price) values ('Suspect', 50);
insert into book (title, price) values ('Comancheros, The', 48);
insert into book (title, price) values ('Flash Gordon''s Trip to Mars', 16);
insert into book (title, price) values ('Valerie', 18);
insert into book (title, price) values ('Sarah Silverman:  We Are Miracles', 49);
insert into book (title, price) values ('Alla älskar Alice', 44);
insert into book (title, price) values ('The Little Polar Bear: Lars and the Little Tiger', 29);
insert into book (title, price) values ('Leviathan', 19);
insert into book (title, price) values ('M', 49);
insert into book (title, price) values ('Hilton!', 45);
insert into book (title, price) values ('Vice Squad', 10);
insert into book (title, price) values ('Kirikou and the Sorceress (Kirikou et la sorcière)', 19);
insert into book (title, price) values ('Hoodwinked Too! Hood vs. Evil', 30);
insert into book (title, price) values ('Frankenstein', 48);
insert into book (title, price) values ('Double Take', 18);
insert into book (title, price) values ('Proposal, The', 30);
insert into book (title, price) values ('Tarzan the Ape Man', 43);
insert into book (title, price) values ('Favor, The', 44);
insert into book (title, price) values ('Sokkotanssi', 35);
insert into book (title, price) values ('Rookie, The', 38);
insert into book (title, price) values ('Love and Death', 33);
insert into book (title, price) values ('Koran by Heart', 31);
insert into book (title, price) values ('Within Our Gates', 12);
insert into book (title, price) values ('Don''t Go Near the Water', 39);
insert into book (title, price) values ('Brain Dead', 17);
insert into book (title, price) values ('Resident Evil: Apocalypse', 45);
insert into book (title, price) values ('Minion, The', 46);
insert into book (title, price) values ('Wanderers', 35);
insert into book (title, price) values ('Life Less Ordinary, A', 40);
insert into book (title, price) values ('Dolores Claiborne', 47);
insert into book (title, price) values ('Going My Way', 44);
insert into book (title, price) values ('Sarah''s Key (Elle s''appelait Sarah)', 32);
insert into book (title, price) values ('Pink Ribbons, Inc.', 12);
insert into book (title, price) values ('Loves of Pharaoh, The (Das Weib des Pharao)', 48);
insert into book (title, price) values ('Mannequin', 37);
insert into book (title, price) values ('Johnny Got His Gun', 38);
insert into book (title, price) values ('Sinners and Saints', 26);
insert into book (title, price) values ('Coneheads', 20);
insert into book (title, price) values ('Drevo', 25);
insert into book (title, price) values ('Ménilmontant', 12);
insert into book (title, price) values ('Jill the Ripper (Jill Rips)', 14);
insert into book (title, price) values ('Yellow Earth (Huang tu di)', 31);
insert into book (title, price) values ('Perfect Fake, A', 23);