insert into shopping_cart (owner) values ('Catherine');
insert into shopping_cart (owner) values ('Whitney');
insert into shopping_cart (owner) values ('Torrey');
insert into shopping_cart (owner) values ('Norene');
insert into shopping_cart (owner) values ('Lula');
insert into shopping_cart (owner) values ('Lemmie');
insert into shopping_cart (owner) values ('Marylinda');
insert into shopping_cart (owner) values ('Barby');
insert into shopping_cart (owner) values ('Julius');
insert into shopping_cart (owner) values ('Bram');

insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'adventure', '655610669-0', 75, 'Nightmares');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'sci-fi', '470167871-6', 79, 'Rampart');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (7, 'comedy', '295528519-6', 37, 'Bone Collector, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'comedy', '576529051-5', 18, 'Curious Case of Benjamin Button, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (9, 'sci-fi', '968245936-2', 93, 'My Father''s Glory (La gloire de mon père)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'thriller', '879438593-9', 62, 'Lonely Wife, The (Charulata)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'mystery', '602425052-5', 52, 'Grand Tour: Disaster in Time (Timescape)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'action', '491130411-1', 56, 'Children of the Corn: Revelation');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'drama', '724534242-3', 81, 'Strike Up the Band');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'romance', '980746153-7', 34, 'Intimate Lighting (Intimni osvetleni)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'mystery', '866040218-9', 82, 'Letter from an Unknown Woman');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'drama', '419882853-9', 45, 'Zookeeper');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (3, 'horror', '664680732-9', 53, 'Too Late the Hero');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'horror', '159758921-7', 99, 'Black Book (Zwartboek)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'action', '441359678-1', 95, '8 Million Ways to Die');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (8, 'horror', '748772656-8', 55, 'One Good Cop');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (4, 'thriller', '725723637-2', 14, 'Invisible Woman, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'thriller', '611528555-0', 63, 'World According to Monsanto, The (monde selon Monsanto, Le)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'drama', '755105243-7', 35, 'Dr. Akagi (Kanzo sensei)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'mystery', '034157773-1', 15, 'Splice');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (9, 'horror', '093301972-6', 19, 'Edge of Heaven, The (Auf der anderen Seite)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (9, 'action', '105927486-8', 27, 'Tunnel, The (Tunnel, Der)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'thriller', '661270302-4', 66, 'Love Nest, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'sci-fi', '794823472-1', 35, 'Wholly Moses');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'thriller', '005221400-1', 96, 'O Auto da Compadecida (Dog''s Will, A)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'adventure', '284088142-X', 56, 'Adventures of Ichabod and Mr. Toad, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (8, 'comedy', '708209135-4', 54, 'Not of This Earth');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (5, 'mystery', '566560413-5', 70, 'Cinematographer Style');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (7, 'comedy', '901995717-1', 73, 'Mr. Deeds Goes to Town');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'romance', '022793674-4', 47, 'Garlic Is As Good As Ten Mothers');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (5, 'drama', '515189143-X', 96, 'Swindle, The (Bidone, Il)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'romance', '024045797-8', 85, 'Sport, Sport, Sport');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (3, 'sci-fi', '758020231-X', 39, 'Carry on Screaming!');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'thriller', '815555068-0', 28, 'Rendition');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (4, 'comedy', '788939932-4', 89, 'Gentleman''s Agreement');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'romance', '874733896-2', 44, 'She Wouldn''t Say Yes');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'drama', '120780836-9', 34, 'Bullets or Ballots');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (4, 'thriller', '639429504-3', 81, 'Picture of Dorian Gray, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (8, 'adventure', '851129202-0', 48, 'Summer of Sam');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (7, 'romance', '009524137-X', 54, 'Game of Death, The (Le Jeu de la Mort)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (4, 'sci-fi', '011874351-1', 25, 'Man Hunt');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (3, 'drama', '994058109-2', 100, 'Rise of Catherine the Great, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (8, 'romance', '058907223-4', 67, 'Undisputed II: Last Man Standing');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'romance', '470896949-X', 33, 'Delhi-6');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'fantasy', '173707868-6', 80, 'Fan, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (3, 'sci-fi', '639770857-8', 24, 'Alice''s Adventures in Wonderland');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'adventure', '593827099-5', 69, 'Jumpin'' Jack Flash');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'comedy', '772903014-4', 54, 'Randy and the Mob');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'comedy', '553663486-0', 12, 'Voices from the List');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'drama', '783362579-5', 53, 'Almost Man, The (Mer eller mindre mann)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (3, 'action', '339696074-2', 36, 'Margaret''s Museum');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (7, 'romance', '115969607-1', 61, 'Bugmaster (Mushishi)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (7, 'thriller', '778679317-8', 28, 'Living Daylights, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (5, 'drama', '400795467-4', 99, 'Rose Seller, The (La vendedora de rosas)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (8, 'action', '272890813-3', 23, 'People vs. Larry Flynt, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'thriller', '279915611-8', 92, 'Polite People (Kurteist fólk)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'comedy', '872233935-3', 62, 'Rubber Johnny');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'action', '698133159-4', 52, 'Lisa');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'adventure', '704939403-3', 95, 'Slam Dunk Ernest');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'romance', '599810306-8', 70, 'Treeless Mountain');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (5, 'mystery', '457682457-0', 37, 'Devil''s Ground, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'romance', '897710238-3', 18, 'Makai Tensho: Samurai Reincarnation (Makai tenshô)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (4, 'horror', '148439683-9', 47, 'Blue Skies');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'action', '523677440-3', 19, 'Iceman, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (8, 'thriller', '744871149-0', 84, 'Hollywood Homicide');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (7, 'romance', '619316851-6', 87, 'Desert of the Tartars, The (Deserto dei Tartari, Il)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (3, 'thriller', '131467698-9', 85, 'The Indian Fighter');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'adventure', '665226350-5', 66, 'Harvest Month, The (Elokuu)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (3, 'comedy', '782074977-6', 73, 'Cosmic Journey');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'romance', '536654587-0', 87, 'Conspirator, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (4, 'drama', '627894039-6', 68, 'Dakota');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'horror', '559996670-4', 20, 'Horse in the Gray Flannel Suit, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (8, 'action', '811282978-0', 66, 'Cat in Paris, A (Une vie de chat)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (5, 'fantasy', '831435866-5', 37, 'Short Night of the Glass Dolls (La corta notte delle bambole di vetro)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (9, 'fantasy', '989434362-7', 63, 'King of Beggars (Mo jong yuen So Hat-Yi)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'horror', '609419104-8', 45, 'New Barbarians, The (I nuovi barbari)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (3, 'adventure', '018364224-4', 21, 'Film with Me in It, A');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'horror', '832794023-6', 33, 'Comet in Moominland');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (5, 'action', '147452612-8', 100, 'The Phantom of the Opera');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'mystery', '976133740-5', 85, 'Open Range');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (9, 'fantasy', '374089307-9', 22, 'Innocent Lies');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (5, 'romance', '939133125-4', 82, 'What''s Love Got to Do with It?');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'adventure', '488018202-8', 59, 'Wallace & Gromit in The Curse of the Were-Rabbit');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (9, 'drama', '609369917-X', 50, 'Finding Bliss');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'horror', '088171455-0', 68, 'Best Worst Movie');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'thriller', '234160831-0', 71, 'Messenger, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'adventure', '005611547-4', 42, 'Sugar Hill');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (5, 'horror', '116300795-1', 76, '17 Girls (17 filles)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (9, 'action', '498478254-4', 66, 'Movie Days (Bíódagar)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (10, 'romance', '835897344-6', 89, 'Backstairs (Hintertreppe)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (3, 'horror', '912812680-7', 38, 'Watermarks');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (7, 'horror', '151479089-0', 65, 'Suspended Vocation, The (La vocation suspendue)');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (9, 'comedy', '488149590-9', 12, 'Late Phases');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'comedy', '261027194-8', 14, 'One 2 Ka 4');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (8, 'horror', '601414254-1', 52, 'Winter Guest, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (6, 'thriller', '652706642-2', 48, 'Remember the Night');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (2, 'fantasy', '432641837-0', 14, 'Summer of Fear');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (9, 'drama', '937794629-8', 73, 'Bull Durham');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (1, 'sci-fi', '509005090-2', 74, 'Shape of Things to Come, The');
insert into shopping_cart_books (shopping_cart_id, genre, isbn, price, title) values (4, 'adventure', '854579237-9', 84, 'Tender Comrade');
